### ISSUE TITLE
zlib1g-dev and libcairo2-dev required?

### ISSUE THREAD

**Issue by fjp** [guiem/train-tesseract#3]
Following the [official tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling#ubuntu) for compiling tesseract with support for the training tools, it seems that `zlib1g-dev` and `libcairo2-dev` are required. In the Dockerfile these libs are not listed for install. Is there a reason why these libs are missing? Are they not required to compile tesseract?

**Comment by fjp** [comment]
http://www.sk-spell.sk.cx/tesseract-project-dependencies lists tesseract project dependencies. 
`zlib1g-dev` is optional and `libcairo2-dev` is a dependency of [libpango](https://packages.debian.org/de/sid/libpango1.0-dev) which gets installed with the Dockerfile.

**Comment by guiem** [comment]
Thanks for checking this out @fjp ! I was waiting to find a moment to verify your inquiry, I'm really sorry I was too late. But thanks again for checking this out yourself.
