### ISSUE TITLE
Random docker issue 

### ISSUE THREAD

**Issue by iknoorjobs** [guiem/train-tesseract#4]
Hi

I am following your medium article (https://medium.com/@guiem/how-to-train-tesseract-4-ebe5881ff3b7). After running the command `docker-compose -f docker.dev.yml up`, I can't understand what to do and where to execute the next given command `docker exec -ti train-ocr bash` ?

Thanks for help.

P.S. Sorry, I am new to docker.

Regards
Iknoor

**Comment by guiem** [comment]
Hi Iknoor,

In the `docker.dev.yml file` runs the `start.sh` script. This script executes a last command (`tail -f /dev/null`) that leaves the Docker instance "hanging" so you can connect to it. 

Translation:
1. Run `docker-compose -f docker.dev.yml up` in one tab of the terminal and leave it open.
2. Run `docker exec -ti train-ocr bash` (you'll enter the container) and that's where you can execute the following instructions.

Certainly, there could be cleaner ways to do this but it does the trick! 

Please, let me know if you need more details!

**Comment by iknoorjobs** [comment]
Hi @guiem 

Thank you so much for your prompt response.

This is exactly what I am trying to do by running `docker exec -ti train-ocr bash`  in another tab. But it keeps on showing this error even if I am running this command from the repo directory.
Error: `Error response from daemon: No such container: train-ocr`

Any idea what might be the possible reasons?

Thanks 
Iknoor

**Comment by guiem** [comment]
It is really hard to know without more specific information.

Did you make sure to observe that step 1 (`docker-compose -f docker.dev.yml up`) runs smoothly and you don't get any error messages? That's the first thing I would check.

I'll try to rebuild everything from scratch though, to verify that all works as expected.

**Comment by iknoorjobs** [comment]
Yes it runs smoothly till the end when it says `Running hooks in /etc/ca-certificates/update.d... done.`, except there is one message in red in the start that tells `debconf: delaying package configuration, since apt-utils is not installed`
It seems that it's not able to find the container name "train-ocr".

**Comment by iknoorjobs** [comment]
Hi @guiem 

Sorry, there was an issue with my server, the code is

**Comment by guiem** [comment]
I'm glad you could solve it, @iknoorjobs !!!

**Comment by iknoorjobs** [comment]
Yes, and thanks for the awesome work. :)
